name: saglik_haritam
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_1.png
