// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:171031307284:web:c2ddc025dac18928e3b301',
    messagingSenderId: '171031307284',
    projectId: 'saglikharitam-6810e',
    authDomain: 'saglikharitam-6810e.firebaseapp.com',
    storageBucket: 'saglikharitam-6810e.firebasestorage.app',
    measurementId: 'G-PED6Z0LL5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:171031307284:android:2a817c5bf667aa65e3b301',
    messagingSenderId: '171031307284',
    projectId: 'saglikharitam-6810e',
    storageBucket: 'saglikharitam-6810e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:171031307284:ios:5dbc281a5ca83b6ee3b301',
    messagingSenderId: '171031307284',
    projectId: 'saglikharitam-6810e',
    storageBucket: 'saglikharitam-6810e.firebasestorage.app',
    iosBundleId: 'com.example.saglikHaritam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    appId: '1:171031307284:ios:5dbc281a5ca83b6ee3b301',
    messagingSenderId: '171031307284',
    projectId: 'saglikharitam-6810e',
    storageBucket: 'saglikharitam-6810e.firebasestorage.app',
    iosBundleId: 'com.example.saglikHaritam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:171031307284:web:ec6f15f5a0bc261fe3b301',
    messagingSenderId: '171031307284',
    projectId: 'saglikharitam-6810e',
    authDomain: 'saglikharitam-6810e.firebaseapp.com',
    storageBucket: 'saglikharitam-6810e.firebasestorage.app',
    measurementId: 'G-SGJ7K5RYG7',
  );
}
